files = {
    'dklint/pfind.py': {'abspath': 'c:\\work\\github\\dklint\\dklint\\pfind.py',
 'fname': 'dklint/pfind.py',
 'html': 'files/dklint,pfind.html',
 'lines': {16: [{'line': 16,
                 'msg': 'Missing function docstring\n        ',
                 'msg_id': 'C0111',
                 'obj': 'pfind.parents',
                 'symbol': 'missing-docstring'}]},
 'location': 'files/dklint,pfind.py'},
    'dklint/dklint.py': {'abspath': 'c:\\work\\github\\dklint\\dklint\\dklint.py',
 'fname': 'dklint/dklint.py',
 'html': 'files/dklint,dklint.html',
 'lines': {104: [{'line': 104,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'parse_rule',
                  'symbol': 'missing-docstring'}],
           109: [{'line': 109,
                  'msg': "Redefining name 'subst' from outer scope (line 22)\n        ",
                  'msg_id': 'W0621',
                  'obj': 'parse_subst',
                  'symbol': 'redefined-outer-name'},
                 {'line': 109,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'parse_subst',
                  'symbol': 'missing-docstring'}],
           114: [{'line': 114,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'dklint',
                  'symbol': 'missing-docstring'}],
           124: [{'line': 124,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'write_stats',
                  'symbol': 'missing-docstring'}],
           131: [{'line': 131,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'reportgrade',
                  'symbol': 'missing-docstring'}],
           135: [{'line': 135,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'dashify',
                  'symbol': 'missing-docstring'}],
           140: [{'line': 140,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'includesvg',
                  'symbol': 'missing-docstring'}],
           144: [{'line': 144,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'editfn',
                  'symbol': 'missing-docstring'}],
           146: [{'line': 146,
                  'msg': 'Use of eval\n        ',
                  'msg_id': 'W0123',
                  'obj': 'editfn',
                  'symbol': 'eval-used'}],
           149: [{'line': 149,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'indent',
                  'symbol': 'missing-docstring'}],
           169: [{'line': 169,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'replace',
                  'symbol': 'missing-docstring'}],
           177: [{'line': 177,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'project_dir',
                  'symbol': 'missing-docstring'}],
           185: [{'line': 185,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'make_build_lint',
                  'symbol': 'missing-docstring'}],
           192: [{'line': 192,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'cleandir',
                  'symbol': 'missing-docstring'}],
           203: [{'line': 203,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'project_name',
                  'symbol': 'missing-docstring'}],
           211: [{'line': 211,
                  'msg': 'Line too long (84/80)\n        ',
                  'msg_id': 'C0301',
                  'obj': '&#160;',
                  'symbol': 'line-too-long'}],
           214: [{'line': 214,
                  'msg': 'Missing class docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'File',
                  'symbol': 'missing-docstring'},
                 {'line': 214,
                  'msg': 'Too few public methods (1/2)\n        ',
                  'msg_id': 'R0903',
                  'obj': 'File',
                  'symbol': 'too-few-public-methods'}],
           229: [{'line': 229,
                  'msg': 'Missing method docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'File.update',
                  'symbol': 'missing-docstring'}],
           256: [{'line': 256,
                  'msg': 'Missing class docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'Files',
                  'symbol': 'missing-docstring'}],
           257: [{'line': 257,
                  'msg': 'Missing method docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'Files.add',
                  'symbol': 'missing-docstring'}],
           267: [{'line': 267,
                  'msg': "Unused argument 'lintdir'\n        ",
                  'msg_id': 'W0613',
                  'obj': 'position_independence',
                  'symbol': 'unused-argument'}],
           272: [{'line': 272,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'position_independence.regexquote',
                  'symbol': 'missing-docstring'}],
           276: [{'line': 276,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'position_independence.fwdslashify',
                  'symbol': 'missing-docstring'},
                 {'line': 276,
                  'msg': "Unused variable 'fwdslashify'\n        ",
                  'msg_id': 'W0612',
                  'obj': 'position_independence.fwdslashify',
                  'symbol': 'unused-variable'}],
           279: [{'line': 279,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'position_independence.copy_python',
                  'symbol': 'missing-docstring'}],
           284: [{'line': 284,
                  'msg': "No name 'PythonLexer' in module 'pygments.lexers'\n        ",
                  'msg_id': 'E0611',
                  'obj': 'position_independence.copy_python',
                  'symbol': 'no-name-in-module'}],
           285: [{'line': 285,
                  'msg': "No name 'HtmlFormatter' in module 'pygments.formatters'\n        ",
                  'msg_id': 'E0611',
                  'obj': 'position_independence.copy_python',
                  'symbol': 'no-name-in-module'}],
           304: [{'line': 304,
                  'msg': 'Line too long (83/80)\n        ',
                  'msg_id': 'C0301',
                  'obj': '&#160;',
                  'symbol': 'line-too-long'}],
           322: [{'line': 322,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'position_independence.cp_file',
                  'symbol': 'missing-docstring'}],
           323: [{'line': 323,
                  'msg': 'Line too long (82/80)\n        ',
                  'msg_id': 'C0301',
                  'obj': '&#160;',
                  'symbol': 'line-too-long'},
                 {'line': 323,
                  'msg': "Exactly one space required after assignment\n        args =  m.group(2).replace('&lt;/td>', '').replace('&lt;/tr>', '').split('&lt;td>')\n             ^\n        ",
                  'msg_id': 'C0326',
                  'obj': '&#160;',
                  'symbol': 'bad-whitespace'}],
           325: [{'line': 325,
                  'msg': 'Line too long (84/80)\n        ',
                  'msg_id': 'C0301',
                  'obj': '&#160;',
                  'symbol': 'line-too-long'}],
           347: [{'line': 347,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'get_css',
                  'symbol': 'missing-docstring'}],
           415: [{'line': 415,
                  'msg': 'Missing function docstring\n        ',
                  'msg_id': 'C0111',
                  'obj': 'main',
                  'symbol': 'missing-docstring'}]},
 'location': 'files/dklint,dklint.py'},
}
